name: Build Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:stable
  flavor: b1.xlarge

commands:
  - build.cmd -subset clr -a x64 -c release
  - build.cmd libs -c release
  - src\tests\build.cmd Release x64 -priority=0
  - src\tests\run.cmd Release x64
  - build.cmd -subset libs.tests -test -c Release

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  win64:
    paths:
      - artifacts\bin\coreclr\windows.x64.Release\**