name: Build and Test Linux x64

agent:
  type: Unity::VM
  image: platform-foundation/linux-ubuntu-18.04-mono-bokken:latest
  flavor: b1.large

commands:
  - ./build.sh -subset clr+libs+libs.tests -test -a x64 -rc checked -lc release -ci -ninja
  - command: ./src/tests/build.sh x64 checked ci
    retries: 1
  - ./src/tests/run.sh x64 checked
  - ./build.sh clr.paltests
  - ./artifacts/bin/coreclr/$(uname).x64.Debug/paltests/runpaltests.sh $(pwd)/artifacts/bin/coreclr/$(uname).x64.Debug/paltests

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  linux64:
    paths:
      - artifacts/bin/coreclr/**
      - artifacts/repro/**