name: Build and Test Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:latest
  flavor: b1.xlarge

commands:
  - build.cmd -subset clr+libs+libs.tests -test -a x64 -rc checked -lc release -ci
  - src\tests\build.cmd x64 checked ci
  - src\tests\run.cmd x64 checked

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  win64:
    paths:
      - artifacts\bin\coreclr\**
      - artifacts\repro\**