name: Run Library Tests Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:stable
  flavor: b1.xlarge

dependencies:
  - .yamato/build_classlibs_win.yml
  - .yamato/build_windows_x64.yml


commands:
  - build.cmd -subset libs.tests -test -c Release

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"

artifacts: 
  win64:
    paths:
      - artifacts/log/**