{% metadata_file .yamato/Globals.metafile %}
---
name: Test Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:v1.1.6-1025111
  flavor: b1.xlarge

dependencies:
  - path: .yamato/build_windows_x64.yml

commands:
# build/run tests
  - build.cmd libs.tests -test -a x64 -c release -ci
  - src\tests\build.cmd x64 release ci
  - src\tests\run.cmd x64 release

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
