{% metadata_file .yamato/Globals.metafile %}
---
name: Test Windows x64

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:v1.1.7-1038262
  flavor: b1.xlarge

dependencies:
  - path: .yamato/build_windows_x64.yml

commands:
# build/run tests
  - .yamato/scripts/test_windows_x64.cmd
  
triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
