{% metadata_file .yamato/Globals.metafile %}
---
name: Test Windows x86

agent:
  type: Unity::VM
  image: platform-foundation/windows-vs2019-il2cpp-bokken:v1.1.7-1038262
  flavor: b1.xlarge

dependencies:
  - path: .yamato/build_windows_x86.yml

commands:
  - .yamato/scripts/test_windows_x86.cmd

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
