{% metadata_file .yamato/Globals.metafile %}
---
name: Test Linux x64

agent:
  type: Unity::VM
  image: platform-foundation/linux-ubuntu-18.04-mono-bokken:0.1.7-978398
  flavor: b1.large

dependencies:
  - path: .yamato/build_linux_x64.yml

commands:
  - ./.yamato/scripts/test_linux_x64.sh
  
triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
