{% metadata_file .yamato/Globals.metafile %}
---
name: Test OSX x64

agent:
  type: Unity::VM::osx
  image: platform-foundation/mac-bokken:v0.1.8-972754
  flavor: m1.mac

dependencies:
  - path: .yamato/build_osx_x64.yml

commands:
# build/run tests
  - ./.yamato/scripts/test_osx_x64.sh
  
triggers:
  pull_requests:
    - targets:
        only:
          - "unity-main"
